=== cityjson/specs/extensions/extension.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CityJSON Extension specifications v1.1",
  "type": "object",

  "definitions": {

    "Plus": {
      "patternProperties": {
        "(\\+)\\w+": {}
      },
      "additionalProperties": false
    }

  },


  "properties": {
    "type": { "enum": ["CityJSONExtension"] },
    "name": { 
      "type": "string",
      "pattern": "^\\w[a-zA-Z@#0-9._]*$",
      "description": "no spaces allowed"
    },

    "version": { 
      "type": "string",
      "pattern": "^(\\d\\.)(\\d+\\.)?(\\*|\\d+)$"
    },

    "versionCityJSON": { 
      "type": "string",
      "pattern": "^(\\d\\.)(\\d)$"
    },

    "uri": { 
      "type": "string",
      "format": "uri-reference",
      "description": "good to host the extension at a URI so that others can access it"
    },

    "description": { "type": "string" },
    
    "extraRootProperties":{
      "patternProperties": {
        "(\\+|\\@)\\w+": {}
      },
      "additionalProperties": false
    },

    "extraAttributes": {
      "type": "object",
      "properties": {
        "Bridge": { "$ref": "#/definitions/Plus" },
        "BridgeConstructiveElement": { "$ref": "#/definitions/Plus" },
        "BridgeInstallation": { "$ref": "#/definitions/Plus" },
        "BridgePart": { "$ref": "#/definitions/Plus" },
        "BridgeRoom": { "$ref": "#/definitions/Plus" },
        "Building": { "$ref": "#/definitions/Plus" },
        "BuildingPart": { "$ref": "#/definitions/Plus" },
        "BuildingConstructiveElement": { "$ref": "#/definitions/Plus" },
        "BuildingFurniture": { "$ref": "#/definitions/Plus" },
        "BuildingInstallation": { "$ref": "#/definitions/Plus" },
        "BuildingRoom": { "$ref": "#/definitions/Plus" },
        "BuildingStorey": { "$ref": "#/definitions/Plus" },
        "BuildingUnit": { "$ref": "#/definitions/Plus" },
        "CityFurniture": { "$ref": "#/definitions/Plus" },
        "CityObjectGroup": { "$ref": "#/definitions/Plus" },
        "LandUse": { "$ref": "#/definitions/Plus" },
        "OtherConstruction": { "$ref": "#/definitions/Plus" },
        "PlantCover": { "$ref": "#/definitions/Plus" },
        "Railway": { "$ref": "#/definitions/Plus" },
        "Road": { "$ref": "#/definitions/Plus" },
        "SolitaryVegetationObject": { "$ref": "#/definitions/Plus" },
        "TINRelief": { "$ref": "#/definitions/Plus" },
        "TransportSquare": { "$ref": "#/definitions/Plus" },
        "Tunnel": { "$ref": "#/definitions/Plus" },
        "TunnelConstructiveElement": { "$ref": "#/definitions/Plus" },
        "TunnelFurnite": { "$ref": "#/definitions/Plus" },
        "TunnelHollowSpace": { "$ref": "#/definitions/Plus" },
        "TunnelInstallation": { "$ref": "#/definitions/Plus" },
        "TunnelPart": { "$ref": "#/definitions/Plus" },
        "WaterBody": { "$ref": "#/definitions/Plus" }
      },
      "additionalProperties": false
    },

    "extraCityObjects": {
      "patternProperties": {
        "(\\+)([A-Z])\\w+": {}
      },
      "additionalProperties": false
    }

  },
  
  "required": ["type", "name", "version", "versionCityJSON", "uri", "extraRootProperties", "extraAttributes",  "extraCityObjects"]
}

=== cityjson/specs/extensions/11/generic.ext.json
{
  "type": "CityJSONExtension",
  "name": "Generic",
  "uri": "https://www.cityjson.org/extensions/download/generic.ext.json",
  "version": "1.0.1",
  "versionCityJSON": "1.1",
  "description": "Extension to handle GenericCityObject; meant as a template to learn how to construct an Extension",
  
  "extraRootProperties": {},     
  
  "extraAttributes": {},

  "extraCityObjects": {
    "+GenericCityObject": {
      "allOf": [
        { "$ref": "cityobjects.schema.json#/_AbstractCityObject" },
        {
          "properties": {
            "type": { "enum": [ "+GenericCityObject" ] },
            "attributes": {
              "type": "object",
              "properties": {
                "my-attribute": { "type": "string" }
              }
            },
            "geometry": {
              "type": "array",
              "items": {
                "oneOf": [
                  { "$ref": "geomprimitives.schema.json#/MultiPoint" },
                  { "$ref": "geomprimitives.schema.json#/MultiLineString" },
                  { "$ref": "geomprimitives.schema.json#/MultiSurface" },
                  { "$ref": "geomprimitives.schema.json#/CompositeSurface" },
                  { "$ref": "geomprimitives.schema.json#/Solid" },
                  { "$ref": "geomprimitives.schema.json#/MultiSolid" },
                  { "$ref": "geomprimitives.schema.json#/CompositeSolid" },
                  { "$ref": "geomprimitives.schema.json#/GeometryInstance" }
                ]
              }
            }
          },
          "required": [ "type" ]
        }
      ]
    }
  }
}
